# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import remote_control_pb2 as remote__control__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in remote_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemoteControllerStub(object):
    """The remote control service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMousePosition = channel.unary_unary(
                '/remote_control.RemoteController/GetMousePosition',
                request_serializer=remote__control__pb2.EmptyRequest.SerializeToString,
                response_deserializer=remote__control__pb2.MousePosition.FromString,
                _registered_method=True)
        self.MoveMouse = channel.unary_unary(
                '/remote_control.RemoteController/MoveMouse',
                request_serializer=remote__control__pb2.MousePosition.SerializeToString,
                response_deserializer=remote__control__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.ClickMouse = channel.unary_unary(
                '/remote_control.RemoteController/ClickMouse',
                request_serializer=remote__control__pb2.TextInput.SerializeToString,
                response_deserializer=remote__control__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.SendText = channel.unary_unary(
                '/remote_control.RemoteController/SendText',
                request_serializer=remote__control__pb2.TextInput.SerializeToString,
                response_deserializer=remote__control__pb2.EmptyResponse.FromString,
                _registered_method=True)


class RemoteControllerServicer(object):
    """The remote control service definition.
    """

    def GetMousePosition(self, request, context):
        """Gets the current mouse position
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveMouse(self, request, context):
        """Moves the mouse to a specific position
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClickMouse(self, request, context):
        """Click
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendText(self, request, context):
        """Sends a string of text to be typed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMousePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMousePosition,
                    request_deserializer=remote__control__pb2.EmptyRequest.FromString,
                    response_serializer=remote__control__pb2.MousePosition.SerializeToString,
            ),
            'MoveMouse': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveMouse,
                    request_deserializer=remote__control__pb2.MousePosition.FromString,
                    response_serializer=remote__control__pb2.EmptyResponse.SerializeToString,
            ),
            'ClickMouse': grpc.unary_unary_rpc_method_handler(
                    servicer.ClickMouse,
                    request_deserializer=remote__control__pb2.TextInput.FromString,
                    response_serializer=remote__control__pb2.EmptyResponse.SerializeToString,
            ),
            'SendText': grpc.unary_unary_rpc_method_handler(
                    servicer.SendText,
                    request_deserializer=remote__control__pb2.TextInput.FromString,
                    response_serializer=remote__control__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remote_control.RemoteController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('remote_control.RemoteController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteController(object):
    """The remote control service definition.
    """

    @staticmethod
    def GetMousePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remote_control.RemoteController/GetMousePosition',
            remote__control__pb2.EmptyRequest.SerializeToString,
            remote__control__pb2.MousePosition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveMouse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remote_control.RemoteController/MoveMouse',
            remote__control__pb2.MousePosition.SerializeToString,
            remote__control__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClickMouse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remote_control.RemoteController/ClickMouse',
            remote__control__pb2.TextInput.SerializeToString,
            remote__control__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remote_control.RemoteController/SendText',
            remote__control__pb2.TextInput.SerializeToString,
            remote__control__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
