# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: remote_control.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'remote_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14remote_control.proto\x12\x0eremote_control\"\x0e\n\x0c\x45mptyRequest\"\x0f\n\rEmptyResponse\"%\n\rMousePosition\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x19\n\tTextInput\x12\x0c\n\x04text\x18\x01 \x01(\t2\xc4\x02\n\x10RemoteController\x12Q\n\x10GetMousePosition\x12\x1c.remote_control.EmptyRequest\x1a\x1d.remote_control.MousePosition\"\x00\x12K\n\tMoveMouse\x12\x1d.remote_control.MousePosition\x1a\x1d.remote_control.EmptyResponse\"\x00\x12H\n\nClickMouse\x12\x19.remote_control.TextInput\x1a\x1d.remote_control.EmptyResponse\"\x00\x12\x46\n\x08SendText\x12\x19.remote_control.TextInput\x1a\x1d.remote_control.EmptyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remote_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=40
  _globals['_EMPTYREQUEST']._serialized_end=54
  _globals['_EMPTYRESPONSE']._serialized_start=56
  _globals['_EMPTYRESPONSE']._serialized_end=71
  _globals['_MOUSEPOSITION']._serialized_start=73
  _globals['_MOUSEPOSITION']._serialized_end=110
  _globals['_TEXTINPUT']._serialized_start=112
  _globals['_TEXTINPUT']._serialized_end=137
  _globals['_REMOTECONTROLLER']._serialized_start=140
  _globals['_REMOTECONTROLLER']._serialized_end=464
# @@protoc_insertion_point(module_scope)
